const DRONES = [
  { name: "DJI Mini 3 Pro", slug: "dji-mini-3-pro" },
  { name: "Mavic Mini", slug: "mavic-mini" },
  { name: "Phantom 3 4K", slug: "phantom-3-4K" },
  { name: "Phantom 3 Standard", slug: "phantom-3-standard" },
  { name: "DJI FlyCart 30", slug: "dji-flycart-30" },
  { name: "DJI Mini 3", slug: "dji-mini-3" },
  { name: "M300 Series", slug: "m300-series" },
  { name: "T100", slug: "mg-new-t100" },
  { name: "M100", slug: "m100" },
  { name: "DJI Matrice 400", slug: "m-400" },
  { name: "Phantom 4", slug: "phantom-4" },
  { name: "DJI Mavic 3", slug: "dji-mavic-3" },
  { name: "Mavic 2", slug: "mavic-2" },
  { name: "DJI Matrice 4D/4TD", slug: "dji-matrice-4d-4td" },
  { name: "DJI Neo", slug: "dji-neo" },
  { name: "DJI Mini 4 Pro", slug: "dji-mini-4-pro" },
  { name: "DJI Air 3", slug: "dji-air-3" },
  { name: "DJI Mavic 3 Pro", slug: "dji-mavic-3-pro" },
  { name: "MG 1S/1A/1P/1P RTK/T16/T20", slug: "mg1p" },
  { name: "DJI Matrice 3D/3TD", slug: "dji-matrice-3d-3td" },
  { name: "DJI Mavic 3 Classic", slug: "dji-mavic-3-classic" },
  { name: "DJI Air 2S", slug: "dji-air-2s" },
  { name: "DJI Mini 4K", slug: "dji-mini-4k" },
  { name: "Spark", slug: "spark" },
  { name: "T70/T70P", slug: "mg-new-t70" },
  { name: "T10", slug: "mg-new-t10" },
  { name: "M600 Series", slug: "m600-series" },
  { name: "Inspire 2", slug: "inspire-2" },
  { name: "Phantom 3 SE", slug: "phantom-3-se" },
  { name: "DJI Flip", slug: "dji-flip" },
  { name: "M350 RTK", slug: "m350-rtk" },
  { name: "Inspire 3", slug: "inspire-3" },
  { name: "T25P", slug: "mg-new-t25p" },
  { name: "DJI FPV", slug: "dji-fpv" },
  { name: "Phantom 3 Pro", slug: "phantom-3-pro" },
  { name: "Phantom 4 Pro", slug: "phantom-4-pro" },
  { name: "DJI Avata 2", slug: "dji-avata-2" },
  { name: "T40", slug: "mg-new-t40" },
  { name: "T30", slug: "mg-new-t30" },
  { name: "Phantom 4 Multispectral", slug: "phantom-4-multispectral" },
  { name: "Phantom 4 RTK", slug: "phantom-4-rtk" },
  { name: "DJI Matrice 4T/4E", slug: "dji-matrice-4t-4e" },
  { name: "DJI Air 3S", slug: "dji-air-3s" },
  { name: "Inspire 1 Series", slug: "inspire-1-series" },
  { name: "Mavic 2 Enterprise", slug: "mavic-2-enterprise" },
  { name: "DJI Mavic 4 Pro", slug: "dji-mavic-4-pro" },
  { name: "T60", slug: "mg-new-t60" },
  { name: "DJI Mavic 3E/3T/3M/3TA", slug: "industry-260" },
  { name: "DJI Avata", slug: "dji-avata" },
  { name: "T50", slug: "mg-new-t50" },
  { name: "T25", slug: "mg-new-t25" },
  { name: "M30 Series", slug: "m30-series" },
  { name: "T20P", slug: "mg-new" },
  { name: "Phantom 4 Advanced", slug: "phantom-4-advanced" },
  { name: "DJI Mini 5 pro", slug: "dji-mini-5-pro" },
  { name: "M200 Series", slug: "m200-series" },
  { name: "Phantom 3 Advanced", slug: "phantom-3-advanced" },
  { name: "Mavic Air", slug: "mavic-air" },
  { name: "DJI FlyCart 100", slug: "dji-flycart-100" },
  { name: "DJI Mini SE", slug: "dji-mini-se" },
  { name: "Mavic Air 2", slug: "mavic-air-2" },
  { name: "DJI Mini 2/DJI Mini 2 SE", slug: "dji-mini-2" },
  { name: "Phantom 4 Pro V2/V2+", slug: "phantom-4-pro-v2" },
  { name: "Mavic Pro", slug: "mavic-pro" }
];

module.exports = {
  DRONES
};
