openapi: 3.0.1
info:
  title: Auth APIs
  description: 管理员与普通用户的注册、登录以及个人资料接口。
  version: 1.0.0
servers:
  - url: /api
security:
  - bearerAuth: []
paths:
  /api/auth/register:
    post:
      summary: 注册管理员
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /api/auth/login:
    post:
      summary: 登录获取JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseAuthResponse'
  /api/auth/profile:
    get:
      summary: 获取管理员资料
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseAdminProfileResponse'
  /api/admin/users:
    get:
      summary: 分页获取所有普通用户
      description: 仅管理员可调用，根据注册时间排序返回普通用户列表，默认按注册时间倒序排列。
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
          description: 页码，从 0 开始。
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
          description: 每页数量，默认 20。
        - in: query
          name: sortOrder
          schema:
            type: string
            enum: [ASC, DESC]
          description: 注册时间排序方向，默认 DESC。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseUserSummaryPageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /api/admin/users/search:
    get:
      summary: 按关键字搜索普通用户
      description: 仅管理员可调用，对用户名或 featureCode 进行模糊匹配并返回结果列表。
      parameters:
        - in: query
          name: keyword
          schema:
            type: string
          required: true
          description: 用于匹配用户名或 featureCode 的关键字。
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
          description: 页码，从 0 开始。
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
          description: 每页数量，默认 20。
        - in: query
          name: sortOrder
          schema:
            type: string
            enum: [ASC, DESC]
          description: 注册时间排序方向，默认 DESC。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseUserSummaryPageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
    put:
      summary: 修改管理员资料
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseAdminProfileResponse'
  /api/auth/weapp/config:
    get:
      summary: 获取小程序相关密钥
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseWeappConfigResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
    post:
      summary: 设置小程序相关密钥
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeappConfigRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /api/user/register:
    post:
      summary: 注册普通用户
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequest'
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /api/user/login:
    post:
      summary: 用户登录获取JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseAuthResponse'
  /api/user/profile:
    get:
      summary: 获取用户资料
      description: 返回用户基础信息以及从 FLP 余额表读取的 flpBalance 虚拟代币余额。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseUserProfileResponse'
    put:
      summary: 修改用户资料
      description: 仅允许更新邮箱、手机号和头像，FLP 点数需通过专用接口调整，无法在此处修改。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateProfileRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseUserProfileResponse'
  /api/weapp/login:
    post:
      summary: 小程序用户登录
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeappLoginRequest'
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseWeappLoginResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        avatarUrl:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    UpdateProfileRequest:
      type: object
      properties:
        email:
          type: string
        avatarUrl:
          type: string
    UserRegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        phone:
          type: string
        avatarUrl:
          type: string
        inviteCode:
          type: string
    UserUpdateProfileRequest:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
        avatarUrl:
          type: string
    AdminProfileResponse:
      type: object
      properties:
        username:
          type: string
        role:
          type: string
        avatarUrl:
          type: string
        email:
          type: string
    AuthResponse:
      type: object
      properties:
        token:
          type: string
        loginSeq:
          type: string
    UserProfileResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        avatarUrl:
          type: string
        featureCode:
          type: string
        status:
          type: string
        online:
          type: boolean
        flpBalance:
          type: number
          format: double
          description: 来自 FLP 余额表的只读虚拟代币余额。
    UserSummaryResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        avatarUrl:
          type: string
        featureCode:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
          description: 用户注册时间。
    UserSummaryPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/UserSummaryResponse'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    ApiResponseAdminProfileResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          $ref: '#/components/schemas/AdminProfileResponse'
    ApiResponseAuthResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          $ref: '#/components/schemas/AuthResponse'
    ApiResponseUserProfileResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          $ref: '#/components/schemas/UserProfileResponse'
    ApiResponseUserSummaryPageResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          $ref: '#/components/schemas/UserSummaryPageResponse'
    ApiResponseWeappLoginResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
        data:
          $ref: '#/components/schemas/WeappLoginResponse'
    WeappLoginRequest:
      type: object
      properties:
        code:
          type: string
        nickname:
          type: string
        avatarUrl:
          type: string
    WeappLoginResponse:
      type: object
      properties:
        token:
          type: string
        userId:
          type: integer
          format: int64
        username:
          type: string
        featureCode:
          type: string
    WeappConfigRequest:
      type: object
      properties:
        appId:
          type: string
        secret:
          type: string
        jwtSecret:
          type: string
    WeappConfigResponse:
      type: object
      properties:
        appId:
          type: string
        secret:
          type: string
        jwtSecret:
          type: string
    ApiResponseWeappConfigResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          $ref: '#/components/schemas/WeappConfigResponse'
    ApiResponseObject:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          nullable: true
