openapi: 3.0.1
info:
  title: FLP 点数 APIs
  description: 管理 FLP 虚拟代币余额及日志的接口。
  version: 1.0.0
servers:
  - url: /api
security:
  - bearerAuth: []
paths:
  /api/flp/adjust:
    post:
      summary: 调整指定用户的 FLP 点数余额
      description: 仅管理员可调用。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlpAdjustRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFlpAdjustResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /api/flp/pay:
    post:
      summary: 使用 FLP 点数支付订单
      description: 普通或微信用户调用，系统会生成 FLP 类型的订单、扣除点数并记录日志。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlpPayRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFlpPayResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /api/flp/logs:
    get:
      summary: 分页查询 FLP 点数操作日志
      description: |
        - 管理员调用时可查看全部日志，并可通过 `featureCode` 参数筛选；返回结果中的每条日志都会包含对应的用户信息。
        - 普通或微信用户调用时仅能查看自身 `featureCode` 下的日志记录，忽略请求中的 `featureCode` 参数。
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
          description: 页码，从 0 开始。
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
          description: 每页条数。
        - in: query
          name: featureCode
          schema:
            type: string
          description: 要过滤的用户特征码，仅管理员查询时生效。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponsePageFlpLogResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    FlpAdjustRequest:
      type: object
      required:
        - featureCode
        - amount
        - operation
      properties:
        featureCode:
          type: string
          description: 用户特征码。
        amount:
          type: number
          format: double
          description: 调整的点数，正数，可包含小数。
        operation:
          type: string
          description: 调整类型，取值 INCREASE 或 DECREASE。
        reason:
          type: string
          description: 调整原因，选填。
    FlpAdjustResponse:
      type: object
      properties:
        featureCode:
          type: string
        balance:
          type: number
          format: double
        amount:
          type: number
          format: double
        operation:
          type: string
    FlpPayRequest:
      type: object
      required:
        - featureCode
        - type
        - referenceId
        - amount
      properties:
        featureCode:
          type: string
          description: 用户特征码。
        type:
          type: string
          description: 订单类型，对应系统内的 `OrderType` 枚举。
        referenceId:
          type: string
          description: 业务关联 ID，例如标注记录 ID。
        amount:
          type: number
          format: double
          description: 本次支付需要扣除的 FLP 点数。
        reason:
          type: string
          description: 支付理由，将写入 FLP 日志。
    FlpPayResponse:
      type: object
      properties:
        orderId:
          type: string
        orderNumber:
          type: string
        amount:
          type: number
          format: double
        remainingBalance:
          type: number
          format: double
    FlpLogResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        featureCode:
          type: string
        operation:
          type: string
        amount:
          type: number
          format: double
        reason:
          type: string
        createdAt:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/FlpLogUserResponse'
    FlpLogUserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        avatarUrl:
          type: string
        featureCode:
          type: string
        status:
          type: string
    PageFlpLogResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/FlpLogResponse'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    ApiResponseFlpAdjustResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          $ref: '#/components/schemas/FlpAdjustResponse'
    ApiResponsePageFlpLogResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          $ref: '#/components/schemas/PageFlpLogResponse'
    ApiResponseFlpPayResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          $ref: '#/components/schemas/FlpPayResponse'
    ApiResponseObject:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          additionalProperties:
            type: string
        data:
          nullable: true
